[env]
RUST_BACKTRACE = "1"
PKG_CONFIG_PATH = { value = "/homebrew/alsa-lib/1.2.13/lib/pkgconfig:/homebrew/libxkbcommon/1.8.1/lib/pkgconfig", force = true }

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false
